export const HOME_PAGE = '/'
export const NATIONAL_TEAMS_PAGE = '/national_teams'
export const CLUBS_PAGE = '/clubs'
export const NATIONAL_TOURNAMENTS_PAGE = '/national_tournaments'
export const SIMULATOR_PAGE = '/simulator'